# Generated by Django 5.2.3 on 2026-01-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='直播日期，格式：YYYY-MM-DD', unique=True, verbose_name='直播日期')),
                ('title', models.CharField(help_text='直播标题，如：咻咻满-2025年11月30日-录播', max_length=200, verbose_name='直播标题')),
                ('summary', models.TextField(blank=True, help_text='直播简介或描述', verbose_name='直播简介')),
                ('bvid', models.CharField(blank=True, help_text='B站视频的BV号', max_length=20, null=True, verbose_name='B站视频BV号')),
                ('duration_seconds', models.IntegerField(blank=True, help_text='直播总时长，单位：秒', null=True, verbose_name='直播时长（秒）')),
                ('duration_formatted', models.CharField(blank=True, help_text='格式化后的时长，如：3h4m50s', max_length=50, verbose_name='直播时长（格式化）')),
                ('parts', models.IntegerField(default=1, help_text='B站视频的分段数，用于前端生成播放链接', verbose_name='视频分段数')),
                ('live_moment', models.CharField(blank=True, help_text='LiveMoment 图册目录路径，如：/gallery/LiveMoment/2025/11/30/', max_length=500, verbose_name='LiveMoment 图册目录')),
                ('view_count', models.CharField(blank=True, default='N/A', help_text='观看人数，如：1.2万', max_length=50, verbose_name='观看人数')),
                ('danmaku_count', models.CharField(blank=True, default='N/A', help_text='弹幕总数，如：3.5万', max_length=50, verbose_name='弹幕数')),
                ('start_time', models.TimeField(blank=True, help_text='开播时间，如：20:00:00', null=True, verbose_name='开播时间')),
                ('end_time', models.TimeField(blank=True, help_text='下播时间，如：23:30:00', null=True, verbose_name='下播时间')),
                ('danmaku_cloud_url', models.CharField(blank=True, help_text='弹幕云图分析结果图片URL', max_length=500, verbose_name='弹幕云图URL')),
                ('is_active', models.BooleanField(default=True, help_text='是否在直播日历中显示', verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, help_text='排序字段，数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '直播记录',
                'verbose_name_plural': '直播记录',
                'db_table': 'livestream',
                'ordering': ['-date', '-sort_order'],
                'indexes': [models.Index(fields=['date'], name='livestream_date_443a75_idx'), models.Index(fields=['-date'], name='livestream_date_078a6a_idx')],
            },
        ),
    ]
