# Generated by Django 5.2.3 on 2026-01-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='cover_url',
            field=models.CharField(blank=True, help_text='直播回放的封面图片URL', max_length=300, null=True, verbose_name='回放封面URL'),
        ),
    ]
