# Generated by Django 5.2.3 on 2026-05-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0002_livestream_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='room_id',
            field=models.CharField(blank=True, default='', help_text='B站直播间房间号，用于关联粉丝出勤数据', max_length=20, verbose_name='B站直播间房间号'),
        ),
    ]
