# Generated by Django 5.2 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('singer', models.CharField(max_length=100, verbose_name='歌手')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('style', models.CharField(max_length=50, verbose_name='曲风')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['song_name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=500, verbose_name='图片URL')),
                ('position', models.IntegerField(choices=[(1, '头像图标'), (2, '背景图片')], verbose_name='位置')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]