# Generated by Django 5.2.3 on 2026-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['artist', 'song_name'], 'verbose_name': '歌曲', 'verbose_name_plural': '歌曲'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='artist',
            field=models.CharField(choices=[('bingjie', '冰洁'), ('youyou', '乐游')], default='bingjie', max_length=50, verbose_name='歌单歌手'),
        ),
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.CharField(choices=[('bingjie', '冰洁'), ('youyou', '乐游')], default='bingjie', max_length=50, verbose_name='歌单歌手'),
        ),
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(max_length=100, verbose_name='原唱歌手'),
        ),
        migrations.AlterUniqueTogether(
            name='sitesetting',
            unique_together={('artist', 'position')},
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist'], name='songlist_so_artist_69a99d_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', 'language'], name='songlist_so_artist_06055a_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', 'style'], name='songlist_so_artist_4dd3a3_idx'),
        ),
    ]
