# Generated by Django 5.2.3 on 2026-01-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_alter_song_options_sitesetting_artist_song_artist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BingjieSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=500, verbose_name='图片URL')),
                ('position', models.IntegerField(choices=[(1, '头像图标'), (2, '背景图片')], verbose_name='位置')),
            ],
            options={
                'verbose_name': '冰洁网站设置',
                'verbose_name_plural': '冰洁网站设置',
            },
        ),
        migrations.CreateModel(
            name='BingjieSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('singer', models.CharField(max_length=100, verbose_name='原唱歌手')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('style', models.CharField(max_length=50, verbose_name='曲风')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '冰洁歌曲',
                'verbose_name_plural': '冰洁歌曲',
            },
        ),
        migrations.CreateModel(
            name='YouyouSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=500, verbose_name='图片URL')),
                ('position', models.IntegerField(choices=[(1, '头像图标'), (2, '背景图片')], verbose_name='位置')),
            ],
            options={
                'verbose_name': '乐游网站设置',
                'verbose_name_plural': '乐游网站设置',
            },
        ),
        migrations.CreateModel(
            name='YouyouSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('singer', models.CharField(max_length=100, verbose_name='原唱歌手')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('style', models.CharField(max_length=50, verbose_name='曲风')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '乐游歌曲',
                'verbose_name_plural': '乐游歌曲',
            },
        ),
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
