# Generated by Django 5.2.3 on 2026-01-12 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0003_bingjiesitesetting_bingjiesong_youyousitesetting_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bingjiesong',
            options={'ordering': ['song_name'], 'verbose_name': '冰洁歌曲', 'verbose_name_plural': '冰洁歌曲'},
        ),
        migrations.AlterModelOptions(
            name='youyousong',
            options={'ordering': ['song_name'], 'verbose_name': '乐游歌曲', 'verbose_name_plural': '乐游歌曲'},
        ),
    ]
