# Generated by Django 5.2.3 on 2026-01-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0004_alter_bingjiesong_options_alter_youyousong_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='youyousitesetting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='songlist/youyou/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='bingjiesitesetting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='songlist/bingjie/', verbose_name='图片'),
        ),
    ]
