# Generated by Django 5.2.3 on 2026-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0005_add_photo_field_to_sitesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingjiesitesetting',
            name='photo_url',
            field=models.CharField(blank=True, help_text='如果上传了图片，此字段将自动填充', max_length=500, verbose_name='图片URL'),
        ),
        migrations.AlterField(
            model_name='youyousitesetting',
            name='photo_url',
            field=models.CharField(blank=True, help_text='如果上传了图片，此字段将自动填充', max_length=500, verbose_name='图片URL'),
        ),
    ]
