# Generated by Django 5.2.5 on 2026-03-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0006_alter_bingjiesitesetting_photo_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaojingbiSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='songlist/baojingbi/', verbose_name='图片')),
                ('photo_url', models.CharField(blank=True, help_text='如果上传了图片，此字段将自动填充', max_length=500, verbose_name='图片URL')),
                ('position', models.IntegerField(choices=[(1, '头像图标'), (2, '背景图片')], verbose_name='位置')),
            ],
            options={
                'verbose_name': '爆金币网站设置',
                'verbose_name_plural': '爆金币网站设置',
            },
        ),
        migrations.CreateModel(
            name='BaojingbiSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('singer', models.CharField(max_length=100, verbose_name='原唱歌手')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('style', models.CharField(max_length=50, verbose_name='曲风')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '爆金币歌曲',
                'verbose_name_plural': '爆金币歌曲',
                'ordering': ['song_name'],
            },
        ),
        migrations.CreateModel(
            name='EvaSiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='songlist/eva/', verbose_name='图片')),
                ('photo_url', models.CharField(blank=True, help_text='如果上传了图片，此字段将自动填充', max_length=500, verbose_name='图片URL')),
                ('position', models.IntegerField(choices=[(1, '头像图标'), (2, '背景图片')], verbose_name='位置')),
            ],
            options={
                'verbose_name': '阿肆网站设置',
                'verbose_name_plural': '阿肆网站设置',
            },
        ),
        migrations.CreateModel(
            name='EvaSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('singer', models.CharField(max_length=100, verbose_name='原唱歌手')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('style', models.CharField(max_length=50, verbose_name='曲风')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '阿肆歌曲',
                'verbose_name_plural': '阿肆歌曲',
                'ordering': ['song_name'],
            },
        ),
    ]
