# Generated by Django 5.2.5 on 2026-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('weibo', '微博'), ('bilibili', 'B站')], help_text='Cookie 对应的平台', max_length=20, unique=True, verbose_name='平台')),
                ('cookie_string', models.TextField(help_text='完整的 Cookie 字符串，从浏览器开发者工具复制', verbose_name='Cookie 字符串')),
                ('is_valid', models.BooleanField(default=True, help_text='Cookie 是否仍然有效', verbose_name='是否有效')),
                ('last_checked', models.DateTimeField(blank=True, null=True, verbose_name='上次检查时间')),
                ('expire_notified', models.BooleanField(default=False, help_text='Cookie 过期后是否已发送邮件通知管理员', verbose_name='已发送过期通知')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '平台 Cookie',
                'verbose_name_plural': '平台 Cookie',
                'db_table': 'moments_platform_cookies',
            },
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('weibo', '微博'), ('bilibili', 'B站')], help_text='动态来源：微博或B站', max_length=20, verbose_name='来源平台')),
                ('source_id', models.CharField(help_text='微博或B站动态的唯一标识', max_length=100, verbose_name='平台原始ID')),
                ('content', models.TextField(help_text='纯文本内容', verbose_name='动态内容')),
                ('images', models.JSONField(default=list, help_text='[{"original_url": "", "thumbnail_url": ""}]', verbose_name='图片列表')),
                ('publish_time', models.DateTimeField(help_text='动态在原平台的发布时间', verbose_name='发布时间')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('share_count', models.IntegerField(default=0, verbose_name='转发数')),
                ('source_url', models.URLField(blank=True, help_text='动态在原平台的链接', verbose_name='原始链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
            ],
            options={
                'verbose_name': '动态',
                'verbose_name_plural': '动态',
                'db_table': 'moments',
                'ordering': ['-publish_time'],
                'indexes': [models.Index(fields=['source', 'publish_time'], name='moments_source_0e0cca_idx'), models.Index(fields=['-publish_time'], name='moments_publish_76b792_idx')],
                'unique_together': {('source', 'source_id')},
            },
        ),
    ]
