# Generated by Django 5.2.5 on 2026-05-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='video_bvid',
            field=models.CharField(blank=True, default='', help_text='当来源为B站且动态包含视频时，保存视频的BV号', max_length=20, verbose_name='B站BV号'),
        ),
    ]
