# Generated by Django 5.2.5 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moments', '0002_moment_video_bvid'),
    ]

    operations = [
        migrations.AddField(
            model_name='moment',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='视频直链地址（如微博MP4），前端用video标签播放', verbose_name='视频直链'),
        ),
    ]
