# Generated by Django 5.2.3 on 2026-01-12 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='曲风名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '曲风',
                'verbose_name_plural': '曲风',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('singer', models.CharField(blank=True, max_length=200, null=True, verbose_name='歌手')),
                ('last_performed', models.DateField(blank=True, null=True, verbose_name='最近演唱时间')),
                ('perform_count', models.IntegerField(default=0, verbose_name='演唱次数')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='语言')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
                'ordering': ['song_name'],
                'indexes': [models.Index(fields=['song_name'], name='song_manage_song_na_6bcda2_idx'), models.Index(fields=['singer'], name='song_manage_singer_59744d_idx'), models.Index(fields=['language'], name='song_manage_languag_0661b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SongRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateField(verbose_name='演唱时间')),
                ('url', models.URLField(blank=True, null=True, verbose_name='视频链接')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('cover_url', models.CharField(blank=True, max_length=300, null=True, verbose_name='封面URL')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='song_management.song', verbose_name='歌曲')),
            ],
            options={
                'verbose_name': '演唱记录',
                'verbose_name_plural': '演唱记录',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='SongStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_styles', to='song_management.song', verbose_name='歌曲')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_songs', to='song_management.style', verbose_name='曲风')),
            ],
            options={
                'verbose_name': '歌曲曲风',
                'verbose_name_plural': '歌曲曲风',
                'unique_together': {('song', 'style')},
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_tags', to='song_management.song', verbose_name='歌曲')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_songs', to='song_management.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '歌曲标签',
                'verbose_name_plural': '歌曲标签',
                'unique_together': {('song', 'tag')},
            },
        ),
    ]
