# Generated by Django 5.2.3 on 2026-01-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='first_perform',
            field=models.DateField(blank=True, null=True, verbose_name='首次演唱时间'),
        ),
    ]
