# Generated by Django 5.2.3 on 2026-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_management', '0002_song_first_perform'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('release_date', models.DateField(verbose_name='发布日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='作品描述')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/original/', verbose_name='封面图片')),
                ('netease_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='网易云音乐 ID')),
                ('bilibili_bvid', models.CharField(blank=True, max_length=50, null=True, verbose_name='B站 BV 号')),
                ('featured', models.BooleanField(default=False, verbose_name='是否精选')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '原创作品',
                'verbose_name_plural': '原创作品',
                'ordering': ['-featured', '-release_date'],
                'indexes': [models.Index(fields=['featured'], name='song_manage_feature_99f7e2_idx'), models.Index(fields=['release_date'], name='song_manage_release_9f61d4_idx'), models.Index(fields=['netease_id'], name='song_manage_netease_9a865b_idx'), models.Index(fields=['bilibili_bvid'], name='song_manage_bilibil_6d1294_idx')],
            },
        ),
    ]
