# Generated by Django 5.2.3 on 2026-02-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_management', '0003_originalwork'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='songrecord',
            index=models.Index(fields=['song', '-performed_at'], name='song_manage_song_id_c68e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='songrecord',
            index=models.Index(fields=['performed_at'], name='song_manage_perform_ca8d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='songstyle',
            index=models.Index(fields=['song'], name='song_manage_song_id_06ae94_idx'),
        ),
        migrations.AddIndex(
            model_name='songstyle',
            index=models.Index(fields=['style'], name='song_manage_style_i_3807e4_idx'),
        ),
        migrations.AddIndex(
            model_name='songstyle',
            index=models.Index(fields=['song', 'style'], name='song_manage_song_id_0c81d5_idx'),
        ),
        migrations.AddIndex(
            model_name='songtag',
            index=models.Index(fields=['song'], name='song_manage_song_id_8fd07b_idx'),
        ),
        migrations.AddIndex(
            model_name='songtag',
            index=models.Index(fields=['tag'], name='song_manage_tag_id_65d9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='songtag',
            index=models.Index(fields=['song', 'tag'], name='song_manage_song_id_e5c533_idx'),
        ),
    ]
