# Generated by Django 5.2.5 on 2026-05-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_management', '0004_songrecord_song_manage_song_id_c68e4c_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-last_performed'], name='song_manage_last_pe_b42576_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-perform_count'], name='song_manage_perform_0b033f_idx'),
        ),
    ]
