# Generated by Django 5.2.3 on 2026-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_management', '0005_song_song_manage_last_pe_b42576_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongRecordLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_record_id', models.IntegerField(db_index=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['song_record_id'], name='song_manage_song_re_62e147_idx'), models.Index(fields=['ip_address', 'song_record_id'], name='song_manage_ip_addr_c539a7_idx'), models.Index(fields=['created_at'], name='song_manage_created_5d5cbf_idx')],
                'unique_together': {('song_record_id', 'ip_address')},
            },
        ),
    ]
