# Generated by Codex on 2026-05-09

import hmac
import re

from django.conf import settings
from django.db import migrations, models

HEX_SHA256_RE = re.compile(r'^[0-9a-f]{64}$')


def hash_legacy_like_identifiers(apps, schema_editor):
    SongRecordLike = apps.get_model('song_management', 'SongRecordLike')
    secret = settings.SECRET_KEY.encode('utf-8')

    for like in SongRecordLike.objects.all().iterator():
        if HEX_SHA256_RE.match(like.ip_address or ''):
            continue

        hashed_identifier = hmac.new(
            secret,
            (like.ip_address or '').encode('utf-8'),
            'sha256',
        ).hexdigest()
        duplicate = SongRecordLike.objects.filter(
            song_record_id=like.song_record_id,
            ip_address=hashed_identifier,
        ).exclude(pk=like.pk).exists()

        if duplicate:
            like.delete()
        else:
            like.ip_address = hashed_identifier
            like.save(update_fields=['ip_address'])


class Migration(migrations.Migration):

    dependencies = [
        ('song_management', '0006_songrecordlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songrecordlike',
            name='ip_address',
            field=models.CharField(max_length=64),
        ),
        migrations.RunPython(hash_legacy_like_identifiers, migrations.RunPython.noop),
    ]
