# Generated by Django 5.2.6 on 2025-09-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0002_work_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': '二创合集', 'verbose_name_plural': '二创合集'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['display_order', '-id'], 'verbose_name': '作品记录', 'verbose_name_plural': '作品记录'},
        ),
        migrations.AddField(
            model_name='collection',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
        migrations.AddField(
            model_name='work',
            name='display_order',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
