# Generated by Django 5.2.6 on 2025-09-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0003_alter_collection_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['position', 'display_order', '-created_at'], 'verbose_name': '二创合集', 'verbose_name_plural': '二创合集'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['position', 'display_order', '-id'], 'verbose_name': '作品记录', 'verbose_name_plural': '作品记录'},
        ),
        migrations.AddField(
            model_name='collection',
            name='position',
            field=models.IntegerField(default=0, verbose_name='位置'),
        ),
        migrations.AddField(
            model_name='work',
            name='position',
            field=models.IntegerField(default=0, verbose_name='位置'),
        ),
    ]
