# Generated by Django 5.2.6 on 2025-09-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0004_alter_collection_options_alter_work_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='封面图片地址'),
        ),
    ]
