# Generated by Django 5.2.6 on 2025-09-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprint', '0005_alter_work_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='cover_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='封面图片地址'),
        ),
    ]
