# Generated by Django 5.2.3 on 2026-01-26 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='图集ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('cover_url', models.CharField(max_length=500, verbose_name='封面图片URL')),
                ('level', models.IntegerField(default=0, verbose_name='层级')),
                ('image_count', models.IntegerField(default=0, verbose_name='图片数量')),
                ('folder_path', models.CharField(max_length=500, verbose_name='文件夹路径')),
                ('tags', models.JSONField(default=list, verbose_name='标签')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.gallery', verbose_name='父图集')),
            ],
            options={
                'verbose_name': '图集',
                'verbose_name_plural': '图集',
                'db_table': 'gallery',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
