# Generated by Django 5.2.3 on 2026-02-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='cover_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='封面图片URL'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='level',
            field=models.IntegerField(default=0, editable=False, verbose_name='层级'),
        ),
    ]
