# Generated by Django 5.2.3 on 2026-01-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawlsession',
            table='data_analytics_crawlsession',
        ),
        migrations.AlterModelTable(
            name='workmetricshour',
            table='data_analytics_workmetricshour',
        ),
        migrations.AlterModelTable(
            name='workstatic',
            table='data_analytics_workstatic',
        ),
    ]
