# Generated by Django 5.2.3 on 2026-01-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0002_alter_crawlsession_table_alter_workmetricshour_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstatic',
            name='cover_url',
            field=models.CharField(blank=True, help_text='支持本地路径（如 /media/data_analytics/covers/xxx.jpg）或外部URL', max_length=500, null=True, verbose_name='封面URL'),
        ),
    ]
