# Generated by Django 5.2.3 on 2026-02-01 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0003_alter_workstatic_cover_url'),
    ]

    operations = [
    ]
