# Generated by Django 5.2.3 on 2026-02-01 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analytics', '0004_auto_20260201_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50, unique=True, verbose_name='账号UID')),
                ('name', models.CharField(max_length=200, verbose_name='账号名称')),
                ('platform', models.CharField(choices=[('bilibili', '哔哩哔哩')], default='bilibili', max_length=50, verbose_name='平台')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '账号配置',
                'verbose_name_plural': '账号配置',
                'db_table': 'data_analytics_account',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['platform', 'uid'], name='data_analyt_platfor_62cc39_idx'), models.Index(fields=['is_active'], name='data_analyt_is_acti_5d7c9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FollowerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.IntegerField(default=0, verbose_name='粉丝数')),
                ('crawl_time', models.DateTimeField(verbose_name='爬取时间')),
                ('ingest_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_analytics.account', verbose_name='账号')),
            ],
            options={
                'verbose_name': '粉丝指标',
                'verbose_name_plural': '粉丝指标',
                'db_table': 'data_analytics_followermetrics',
                'ordering': ['-crawl_time'],
                'indexes': [models.Index(fields=['account', 'crawl_time'], name='data_analyt_account_127bfd_idx'), models.Index(fields=['crawl_time'], name='data_analyt_crawl_t_40b816_idx')],
                'unique_together': {('account', 'crawl_time')},
            },
        ),
    ]
