# Generated by Django 5.2.3 on 2025-06-15 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('singer', models.CharField(blank=True, max_length=200, null=True)),
                ('last_performed', models.DateField(blank=True, null=True)),
                ('perform_count', models.IntegerField(default=0)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='songrecord',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.songs'),
        ),
        migrations.AlterField(
            model_name='songstyle',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.songs'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
