# Generated by Django 5.2.6 on 2025-09-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': '标签表',
                'verbose_name_plural': '标签表',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='songrecord',
            options={'ordering': ['-performed_at'], 'verbose_name': '演唱记录', 'verbose_name_plural': '演唱记录'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['song_name'], 'verbose_name': '歌单', 'verbose_name_plural': '歌单'},
        ),
        migrations.AlterModelOptions(
            name='songstyle',
            options={'verbose_name': '歌曲曲风', 'verbose_name_plural': '歌曲曲风'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['name'], 'verbose_name': '曲风表', 'verbose_name_plural': '曲风表'},
        ),
        migrations.AlterField(
            model_name='songrecord',
            name='cover_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='推荐语内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_songs', models.ManyToManyField(blank=True, help_text='推荐的歌曲', to='main.songs')),
            ],
            options={
                'verbose_name': '推荐语',
                'verbose_name_plural': '推荐语',
            },
        ),
        migrations.CreateModel(
            name='SongTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.songs')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tag')),
            ],
            options={
                'verbose_name': '歌曲标签',
                'verbose_name_plural': '歌曲标签',
                'unique_together': {('song', 'tag')},
            },
        ),
    ]
