# Generated by Django 5.2.6 on 2025-09-16 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_songrecord_cover_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songrecord',
            options={'ordering': ['-performed_at'], 'verbose_name': '演唱记录', 'verbose_name_plural': '演唱记录'},
        ),
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ['song_name'], 'verbose_name': '歌单', 'verbose_name_plural': '歌单'},
        ),
        migrations.AlterModelOptions(
            name='songstyle',
            options={'verbose_name': '歌曲-曲风表', 'verbose_name_plural': '歌曲-曲风表'},
        ),
        migrations.AlterModelOptions(
            name='style',
            options={'ordering': ['name'], 'verbose_name': '曲风表', 'verbose_name_plural': '曲风表'},
        ),
    ]
