# Generated by Django 5.2.3 on 2025-06-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_songs_alter_songrecord_song_alter_songstyle_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
