# Generated by Django 5.2.6 on 2025-09-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_songrecord_options_alter_songs_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='推荐语内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '推荐语',
                'verbose_name_plural': '推荐语',
            },
        ),
    ]
