# Generated by Django 5.2.3 on 2025-10-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='网站图标'),
        ),
    ]
