# Generated by Django 5.2.6 on 2025-09-16 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommended_song',
            field=models.ForeignKey(blank=True, help_text='推荐的歌曲', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.songs'),
        ),
    ]
