# Generated by Django 5.2.3 on 2026-01-06 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_sitesettings_favicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='数据源')),
                ('node_id', models.CharField(max_length=100, verbose_name='节点ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_work_count', models.IntegerField(default=0, verbose_name='总作品数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '爬取会话',
                'verbose_name_plural': '爬取会话',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkMetricsHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('work_id', models.CharField(max_length=100, verbose_name='作品ID')),
                ('crawl_time', models.DateTimeField(verbose_name='爬取时间')),
                ('view_count', models.IntegerField(default=0, verbose_name='播放数')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('coin_count', models.IntegerField(default=0, verbose_name='投币数')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏数')),
                ('danmaku_count', models.IntegerField(default=0, verbose_name='弹幕数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论数')),
                ('session_id', models.IntegerField(verbose_name='会话ID')),
                ('ingest_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '作品小时指标',
                'verbose_name_plural': '作品小时指标',
                'ordering': ['-crawl_time'],
                'indexes': [models.Index(fields=['platform', 'work_id'], name='main_workme_platfor_56d8ed_idx'), models.Index(fields=['crawl_time'], name='main_workme_crawl_t_138905_idx'), models.Index(fields=['session_id'], name='main_workme_session_ade0e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='平台')),
                ('work_id', models.CharField(max_length=100, verbose_name='作品ID')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('publish_time', models.DateTimeField(verbose_name='发布时间')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面URL')),
            ],
            options={
                'verbose_name': '作品静态信息',
                'verbose_name_plural': '作品静态信息',
                'ordering': ['-publish_time'],
                'unique_together': {('platform', 'work_id')},
            },
        ),
    ]
