# Generated by Django 5.2.3 on 2026-01-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_crawlsession_workmetricshour_workstatic'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstatic',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='投稿是否有效'),
        ),
    ]
