# Generated by Django 5.2.6 on 2025-09-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recommendation_recommended_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_song',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='recommended_songs',
            field=models.ManyToManyField(blank=True, help_text='推荐的歌曲', to='main.songs'),
        ),
    ]
