# Generated by Django 5.2.5 on 2026-01-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_workstatic_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_songs',
        ),
        migrations.DeleteModel(
            name='SiteSettings',
        ),
        migrations.DeleteModel(
            name='Recommendation',
        ),
    ]
