# Generated by Django 5.2.6 on 2025-09-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_recommendation_recommended_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='tag',
            field=models.CharField(blank=True, help_text='歌曲标签', max_length=100, null=True),
        ),
    ]
