# Generated by Django 5.2.6 on 2025-09-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tag_songtag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songtag',
            options={'verbose_name': '歌曲标签', 'verbose_name_plural': '歌曲标签'},
        ),
    ]
