# Generated by Django 5.2.6 on 2025-09-17 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_songtag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songstyle',
            options={'verbose_name': '歌曲曲风', 'verbose_name_plural': '歌曲曲风'},
        ),
    ]
