# Generated by Django 5.2.6 on 2025-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_songstyle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='tag',
        ),
    ]
