# Generated by Django 5.2.5 on 2026-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='网站图标')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='推荐语内容')),
                ('is_active', models.BooleanField(default=True, help_text='是否激活显示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_songs', models.ManyToManyField(blank=True, help_text='推荐的歌曲', related_name='recommendations', to='song_management.song')),
            ],
            options={
                'verbose_name': '推荐语',
                'verbose_name_plural': '推荐语',
                'ordering': ['-created_at'],
            },
        ),
    ]
