# Generated by Django 5.2.3 on 2026-01-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('title', models.CharField(max_length=200, verbose_name='里程碑标题')),
                ('description', models.TextField(verbose_name='里程碑描述')),
                ('display_order', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '里程碑',
                'verbose_name_plural': '里程碑',
                'ordering': ['display_order', 'year'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='艺人头像'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_birthday',
            field=models.DateField(blank=True, null=True, verbose_name='艺人生日'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_constellation',
            field=models.CharField(blank=True, max_length=50, verbose_name='星座'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_hobbies',
            field=models.JSONField(default=list, verbose_name='爱好'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='栖息地'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='艺人名称'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_voice_features',
            field=models.JSONField(default=list, verbose_name='声线特色'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bilibili_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='B站链接'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='netease_music_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='网易云音乐链接'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weibo_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='微博链接'),
        ),
    ]
