# Generated by Django 5.2.3 on 2026-01-25 13:31

from django.db import migrations, models


def migrate_year_to_date(apps, schema_editor):
    """将 year 字段迁移到 date 字段"""
    Milestone = apps.get_model('site_settings', 'Milestone')

    for milestone in Milestone.objects.all():
        # 将年份转换为日期（默认为1月1日）
        if milestone.year:
            milestone.date = f"{milestone.year}-01-01"
            milestone.save()


def reverse_migrate_date_to_year(apps, schema_editor):
    """将 date 字段回退到 year 字段"""
    Milestone = apps.get_model('site_settings', 'Milestone')

    for milestone in Milestone.objects.all():
        if milestone.date:
            milestone.year = milestone.date.year
            milestone.save()


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_milestone_sitesettings_artist_avatar_and_more'),
    ]

    operations = [
        # 添加新的 date 字段
        migrations.AddField(
            model_name='milestone',
            name='date',
            field=models.DateField(verbose_name='里程碑日期', null=True),
        ),
        # 迁移数据
        migrations.RunPython(migrate_year_to_date, reverse_migrate_date_to_year),
        # 删除旧的 year 字段
        migrations.RemoveField(
            model_name='milestone',
            name='year',
        ),
        # 将 date 字段设置为非空
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(verbose_name='里程碑日期'),
        ),
    ]
