# Generated by Django 5.2.3 on 2026-01-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_auto_20260125_2131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['-date', 'display_order'], 'verbose_name': '里程碑', 'verbose_name_plural': '里程碑'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='artist_hobbies',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='artist_profession',
            field=models.JSONField(default=list, verbose_name='职业'),
        ),
    ]
