# Generated by Django 5.2.3 on 2026-01-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0004_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='qq_music_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='QQ音乐链接'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='xiaohongshu_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='小红书链接'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='YouTube链接'),
        ),
    ]
