# Generated by Django 5.2.3 on 2026-01-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0005_sitesettings_qq_music_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='douyin_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='抖音链接'),
        ),
    ]
