# Generated by Django 5.2.3 on 2026-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0006_sitesettings_douyin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.qq.com', max_length=200, verbose_name='SMTP服务器')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='SMTP端口')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='使用TLS')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=200, verbose_name='发件邮箱')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=200, verbose_name='SMTP授权码')),
                ('admin_email', models.EmailField(blank=True, default='', max_length=200, verbose_name='管理员邮箱')),
                ('from_email', models.EmailField(blank=True, default='', max_length=200, verbose_name='发件人地址')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '邮箱配置',
                'verbose_name_plural': '邮箱配置',
            },
        ),
    ]
