# Generated by Django 5.2.3 on 2026-05-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0007_emailconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='smtp_password',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='SMTP授权码'),
        ),
    ]
