# Generated by Django 5.2.3 on 2026-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_alter_emailconfig_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='background_active',
            field=models.BooleanField(default=False, verbose_name='启用背景图'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='网站背景图'),
        ),
    ]
