# Generated by Django 5.2.3 on 2026-05-10 01:40

from django.db import migrations, models


def copy_background_to_head(apps, schema_editor):
    SiteSettings = apps.get_model('site_settings', 'SiteSettings')
    for s in SiteSettings.objects.all():
        if s.background_image:
            s.head_background_image = s.background_image.name
        s.head_background_active = s.background_active
        s.save(update_fields=['head_background_image', 'head_background_active'])


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0009_sitesettings_background_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='head_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='顶部背景图'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='head_background_active',
            field=models.BooleanField(default=False, verbose_name='启用顶部背景图'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contain_background_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/', verbose_name='页面背景图'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contain_background_active',
            field=models.BooleanField(default=False, verbose_name='启用页面背景图'),
        ),
        migrations.RunPython(copy_background_to_head, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='sitesettings',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='background_active',
        ),
    ]
