# Generated by Django 5.2.3 on 2026-05-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestream', '0002_livestream_cover_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('bilibili', '哔哩哔哩')], default='bilibili', max_length=20, verbose_name='平台')),
                ('bilibili_uid', models.CharField(max_length=50, unique=True, verbose_name='B站UID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('first_seen_at', models.DateTimeField(blank=True, help_text='用户首次在直播中被记录的时间', null=True, verbose_name='首次出现时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '粉丝画像',
                'verbose_name_plural': '粉丝画像',
                'db_table': 'livefans_fan_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bilibili_uid'], name='livefans_fa_bilibil_190a77_idx'), models.Index(fields=['username'], name='livefans_fa_usernam_a711e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='LiveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_danmaku', models.BooleanField(default=False, verbose_name='是否发弹幕')),
                ('danmaku_count', models.IntegerField(default=0, verbose_name='弹幕数量')),
                ('has_gift', models.BooleanField(default=False, verbose_name='是否投喂礼物')),
                ('has_sc', models.BooleanField(default=False, help_text='醒目留言（Super Chat）', verbose_name='是否发SC')),
                ('has_guard', models.BooleanField(default=False, help_text='上舰/续舰（大航海/舰长）', verbose_name='是否有大航海')),
                ('watch_duration_minutes', models.IntegerField(default=0, help_text='在直播间的观看时长', verbose_name='观看时长（分钟）')),
                ('is_attended', models.BooleanField(default=False, help_text='达成任一条件即为出勤：弹幕/礼物/SC/大航海/观看时长', verbose_name='是否成功出勤')),
                ('first_seen', models.DateTimeField(blank=True, help_text='本场直播中首次被检测到的时间', null=True, verbose_name='首次检测时间')),
                ('last_seen', models.DateTimeField(blank=True, help_text='本场直播中最后一次被检测到的时间', null=True, verbose_name='最后检测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='livefans.fanprofile', verbose_name='粉丝')),
                ('livestream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fan_attendances', to='livestream.livestream', verbose_name='直播场次')),
            ],
            options={
                'verbose_name': '粉丝出勤记录',
                'verbose_name_plural': '粉丝出勤记录',
                'db_table': 'livefans_attendance',
                'ordering': ['-livestream__date'],
                'indexes': [models.Index(fields=['fan', 'livestream'], name='livefans_at_fan_id_a303a0_idx'), models.Index(fields=['livestream', '-danmaku_count'], name='livefans_at_livestr_a26240_idx'), models.Index(fields=['is_attended'], name='livefans_at_is_atte_5c50c9_idx')],
                'unique_together': {('fan', 'livestream')},
            },
        ),
    ]
