# Generated by Django 5.2.3 on 2026-05-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livefans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanprofile',
            name='fan_badge_level',
            field=models.IntegerField(default=0, help_text='B站粉丝勋章等级，0表示无勋章', verbose_name='粉丝勋章等级'),
        ),
    ]
