# Generated by Django 5.2.3 on 2026-05-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livefans', '0002_fanprofile_fan_badge_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.BigIntegerField(unique=True, verbose_name='用户UID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('face', models.CharField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('guard_level', models.IntegerField(help_text='1=总督, 2=提督, 3=舰长', verbose_name='大航海级别')),
                ('guard_type', models.CharField(max_length=20, verbose_name='大航海类型')),
                ('medal_name', models.CharField(blank=True, default='', max_length=50, verbose_name='粉丝牌名称')),
                ('medal_level', models.IntegerField(default=0, verbose_name='粉丝牌等级')),
                ('accompany', models.IntegerField(default=0, verbose_name='陪伴天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '大航海用户',
                'verbose_name_plural': '大航海用户',
                'db_table': 'livefans_guard',
                'ordering': ['guard_level', '-medal_level'],
                'indexes': [models.Index(fields=['guard_level'], name='livefans_gu_guard_l_04ed91_idx'), models.Index(fields=['uid'], name='livefans_gu_uid_ad61d6_idx')],
            },
        ),
    ]
