# Generated by Django 5.2.6 on 2025-12-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bingjie_site_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoURL', models.CharField(max_length=500, verbose_name='图片URL')),
                ('position', models.IntegerField(verbose_name='位置')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='bingjie_Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200, verbose_name='歌曲名称')),
                ('language', models.CharField(max_length=50, verbose_name='语言')),
                ('singer', models.CharField(max_length=100, verbose_name='歌手')),
                ('style', models.CharField(max_length=50, verbose_name='曲风')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '歌曲',
                'verbose_name_plural': '歌曲',
            },
        ),
    ]
